/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as mainLayoutRouteImport } from './routes/(main)/_layout'
import { Route as mainLayoutDashboardRouteImport } from './routes/(main)/_layout.dashboard'
import { Route as mainLayoutSettingsRouteImport } from './routes/(main)/_layout.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutRoute = mainLayoutRouteImport.update({
  id: '/(main)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutDashboardRoute = mainLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutSettingsRoute = mainLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof mainLayoutDashboardRoute
  '/settings': typeof mainLayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof mainLayoutDashboardRoute
  '/settings': typeof mainLayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(main)/_layout': typeof mainLayoutRouteWithChildren
  '/(main)/_layout/dashboard': typeof mainLayoutDashboardRoute
  '/(main)/_layout/settings': typeof mainLayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signup' | '/dashboard' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signup' | '/dashboard' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)/signup'
    | '/(main)/_layout'
    | '/(main)/_layout/dashboard'
    | '/(main)/_layout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authSignupRoute: typeof authSignupRoute
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout': {
      id: '/(main)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout/dashboard': {
      id: '/(main)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainLayoutDashboardRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/settings': {
      id: '/(main)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainLayoutSettingsRouteImport
      parentRoute: typeof mainLayoutRoute
    }
  }
}

interface mainLayoutRouteChildren {
  mainLayoutDashboardRoute: typeof mainLayoutDashboardRoute
  mainLayoutSettingsRoute: typeof mainLayoutSettingsRoute
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  mainLayoutDashboardRoute: mainLayoutDashboardRoute,
  mainLayoutSettingsRoute: mainLayoutSettingsRoute,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authSignupRoute: authSignupRoute,
  mainLayoutRoute: mainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
